### ISSUE TITLE
Multiprocess sampling fails on macOS

### ISSUE THREAD

**Issue by eigenfoo** [eigenfoo/littlemcmc#85]
## Description

**Please provide a minimal, self-contained, and reproducible example.**

```python
import numpy as np
import scipy.stats
import littlemcmc as lmc


def logp_func(x, loc=0, scale=1):
    return np.log(scipy.stats.norm.pdf(x, loc=loc, scale=scale))


def dlogp_func(x, loc=0, scale=1):
    return -(x - loc) / scale


def logp_dlogp_func(x, loc=0, scale=1):
    return logp_func(x, loc=loc, scale=scale), dlogp_func(x, loc=loc, scale=scale)


trace, stats = lmc.sample(logp_dlogp_func=logp_dlogp_func, model_ndim=1)
```

**Please provide the full traceback.**

<details>
  <summary>Click to expand...</summary>

```python
Traceback (most recent call last):-----------------------------------------------------------------| 0.00% [0/8000 00:00<00:00 Sampling 4 chains, 0 divergences]
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
    old_handlers)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    code = spawn._main(child_r)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
Traceback (most recent call last):
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
    run_name="__mp_main__")
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 263, in run_path
    old_handlers)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    code = spawn._main(child_r)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    pkg_name=pkg_name, script_name=fname)
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
Traceback (most recent call last):
    prepare(preparation_data)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    mod_name, mod_spec, pkg_name, script_name)
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    old_handlers)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    run_name="__mp_main__")
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 263, in run_path
    exec(code, run_globals)
  File "/Users/george/littlemcmc/tests/foo.py", line 18, in <module>
    code = spawn._main(child_r)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    trace, stats = lmc.sample(logp_dlogp_func=logp_dlogp_func, model_ndim=1)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 188, in sample
    prepare(preparation_data)
    pkg_name=pkg_name, script_name=fname)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    exec(code, run_globals)
  File "/Users/george/littlemcmc/tests/foo.py", line 18, in <module>
    run_name="__mp_main__")
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 263, in run_path
    trace, stats = lmc.sample(logp_dlogp_func=logp_dlogp_func, model_ndim=1)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 188, in sample
    traces, stats = _mp_sample(**sample_args, **parallel_args)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 300, in _mp_sample
    traces, stats = _mp_sample(**sample_args, **parallel_args)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 300, in _mp_sample
    pkg_name=pkg_name, script_name=fname)
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    pickle_backend=pickle_backend,
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 433, in __init__
    mod_name, mod_spec, pkg_name, script_name)
    pickle_backend=pickle_backend,
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 433, in __init__
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/george/littlemcmc/tests/foo.py", line 18, in <module>
    trace, stats = lmc.sample(logp_dlogp_func=logp_dlogp_func, model_ndim=1)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 188, in sample
    traces, stats = _mp_sample(**sample_args, **parallel_args)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 300, in _mp_sample
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 433, in <listcomp>
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 433, in <listcomp>
    pickle_backend=pickle_backend,
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 433, in __init__
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 278, in __init__
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 278, in __init__
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 433, in <listcomp>
    self._process.start()
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._process.start()
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 278, in __init__
    self._popen = self._Popen(self)
    self._process.start()
    self._popen = self._Popen(self)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    self._popen = self._Popen(self)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    return Popen(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    return Popen(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
    super().__init__(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    super().__init__(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 42, in _launch
    self._launch(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 42, in _launch
    self._launch(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    _check_not_importing_main()
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
    old_handlers)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    code = spawn._main(child_r)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/george/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/george/littlemcmc/tests/foo.py", line 18, in <module>
    trace, stats = lmc.sample(logp_dlogp_func=logp_dlogp_func, model_ndim=1)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 188, in sample
    traces, stats = _mp_sample(**sample_args, **parallel_args)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 300, in _mp_sample
    pickle_backend=pickle_backend,
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 433, in __init__
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 433, in <listcomp>
    for chain, seed, start in zip(range(chains), seeds, start_points)
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 278, in __init__
    self._process.start()
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "tests/foo.py", line 18, in <module>
    trace, stats = lmc.sample(logp_dlogp_func=logp_dlogp_func, model_ndim=1)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 188, in sample
    traces, stats = _mp_sample(**sample_args, **parallel_args)
  File "/Users/george/littlemcmc/littlemcmc/sampling.py", line 305, in _mp_sample
    for draw in sampler:
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 469, in __iter__
    draw = ProcessAdapter.recv_draw(self._active)
  File "/Users/george/littlemcmc/littlemcmc/parallel_sampling.py", line 337, in recv_draw
    msg = ready[0].recv()
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/george/miniconda3/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
  ```

</details>

**Please provide any additional information below.**

- I assume the error is caused by the `recv` but [the other end is already closed.](https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.connection.Connection.recv)
- If I wrap the code in an `if __name__ == "__main__"`, it runs fine.
- This code also runs fine on Linux.

## Environment

* LittleMCMC version: from source
* Python version: 3.7
* Operating system: macOS

**Comment by carlosgmartin** [comment]
@eigenfoo I'm having the same issue. Example:

```python3
from scipy.stats import norm
from littlemcmc import sample

def logp_dlogp(x, loc=0, scale=1):
    return norm.logpdf(x, loc, scale), -(x - loc) / scale

trace, stats = sample(logp_dlogp, 1)
```

My specs are
- macOS Big Sur 11.1
- 2.5 GHz Quad-Core Intel Core i7
- conda 4.9.2
- Python 3.8.5
- SciPy 1.4.1
- LittleMCMC 0.2.2

Wrapping in `__name__ == "__main__"` removes the error, but I get the following warning multiple times:

```
/opt/miniconda3/lib/python3.8/site-packages/littlemcmc/math.py:35: RuntimeWarning: divide by zero encountered in log1p
  return np.where(x < 0.683, np.log(-np.expm1(-x)), np.log1p(-np.exp(-x)))
```
